FROM node:16-alpine

ARG NODE_PORT

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
COPY yarn.lock .

# Bundle app source
COPY . .

# Exports
EXPOSE ${NODE_PORT}
